name: mobile_apps
description: AI Healthcare Assistant for Rural Areas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Google Fonts (Poppins)
  google_fonts: ^6.2.1

  # Local Storage
  shared_preferences: ^2.3.2

  # URL Launcher (for calls, maps)
  url_launcher: ^6.3.0

  # Intl (date formatting)
  intl: ^0.19.0

  # UUID
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
